//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}: {2} (actual)  {3}  {4} (expected).
        /// </summary>
        internal static string APITest_Checkpoint_ActExp {
            get {
                return ResourceManager.GetString("APITest_Checkpoint_ActExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}: {2} (compound).
        /// </summary>
        internal static string APITest_Checkpoint_CompoundValue {
            get {
                return ResourceManager.GetString("APITest_Checkpoint_CompoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string APITest_Checkpoint_EmptyValue {
            get {
                return ResourceManager.GetString("APITest_Checkpoint_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no-operation&gt;.
        /// </summary>
        internal static string APITest_Checkpoint_NoOperation {
            get {
                return ResourceManager.GetString("APITest_Checkpoint_NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to a directory where the raw XML report can be found..
        /// </summary>
        internal static string ArgDesc_InputFile {
            get {
                return ResourceManager.GetString("ArgDesc_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert the raw XML report to JUnit report XML format and
        ///    save the content to the specified file..
        /// </summary>
        internal static string ArgDesc_JUnitFileOption {
            get {
                return ResourceManager.GetString("ArgDesc_JUnitFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show program help..
        /// </summary>
        internal static string ArgDesc_ShowHelpOption {
            get {
                return ResourceManager.GetString("ArgDesc_ShowHelpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show program version..
        /// </summary>
        internal static string ArgDesc_ShowVersionOption {
            get {
                return ResourceManager.GetString("ArgDesc_ShowVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The XML report file &apos;run_results.xml&apos; is not found.
        ///Please run test with &quot;HTML Report&quot; format to generate the XML report file..
        /// </summary>
        internal static string ErrMsg_CannotFindXmlReportFile {
            get {
                return ResourceManager.GetString("ErrMsg_CannotFindXmlReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The first XML node can&apos;t be recognized. The input file is not a valid UFT One test XML report..
        /// </summary>
        internal static string ErrMsg_Input_InvalidFirstReportNode {
            get {
                return ResourceManager.GetString("ErrMsg_Input_InvalidFirstReportNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The GUI test iteration index is invalid: {0}.
        /// </summary>
        internal static string ErrMsg_Input_InvalidGUITestIterationIndex {
            get {
                return ResourceManager.GetString("ErrMsg_Input_InvalidGUITestIterationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read &apos;testrun&apos; report node from the Xml report..
        /// </summary>
        internal static string ErrMsg_Input_MissingTestRunNode {
            get {
                return ResourceManager.GetString("ErrMsg_Input_MissingTestRunNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The JUnit output can&apos;t be a directory.
        /// </summary>
        internal static string ErrMsg_JUnit_OutputCannotDir {
            get {
                return ResourceManager.GetString("ErrMsg_JUnit_OutputCannotDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The output file cannot be same as the input file..
        /// </summary>
        internal static string ErrMsg_JUnit_OutputSameAsInput {
            get {
                return ResourceManager.GetString("ErrMsg_JUnit_OutputSameAsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ErrMsg_Prefix {
            get {
                return ResourceManager.GetString("ErrMsg_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The value is not specified for the option &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorMsg_MissingOptionalArgValue {
            get {
                return ResourceManager.GetString("ErrorMsg_MissingOptionalArgValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The option &apos;{0}&apos; cannot be parsed due to the unsupported type: {1}.
        /// </summary>
        internal static string ErrorMsg_UnknownArgPropertyType {
            get {
                return ResourceManager.GetString("ErrorMsg_UnknownArgPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the input file..
        /// </summary>
        internal static string Exit_CannotReadFile {
            get {
                return ResourceManager.GetString("Exit_CannotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the output file..
        /// </summary>
        internal static string Exit_CannotWriteFile {
            get {
                return ResourceManager.GetString("Exit_CannotWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not found..
        /// </summary>
        internal static string Exit_FileNotFound {
            get {
                return ResourceManager.GetString("Exit_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error occurred..
        /// </summary>
        internal static string Exit_GeneralError {
            get {
                return ResourceManager.GetString("Exit_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument..
        /// </summary>
        internal static string Exit_InvalidArgument {
            get {
                return ResourceManager.GetString("Exit_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is invalid..
        /// </summary>
        internal static string Exit_InvalidInput {
            get {
                return ResourceManager.GetString("Exit_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required argument is missing..
        /// </summary>
        internal static string Exit_MissingArgument {
            get {
                return ResourceManager.GetString("Exit_MissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output format is not specified..
        /// </summary>
        internal static string Exit_UnknownOutputFormat {
            get {
                return ResourceManager.GetString("Exit_UnknownOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result XML file: .
        /// </summary>
        internal static string GUITest_AccCheckpoint_ResultXml {
            get {
                return ResourceManager.GetString("GUITest_AccCheckpoint_ResultXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result XSL file: .
        /// </summary>
        internal static string GUITest_AccCheckpoint_ResultXsl {
            get {
                return ResourceManager.GetString("GUITest_AccCheckpoint_ResultXsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual image file: .
        /// </summary>
        internal static string GUITest_BitmapCheckpoint_ActualImage {
            get {
                return ResourceManager.GetString("GUITest_BitmapCheckpoint_ActualImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference image file: .
        /// </summary>
        internal static string GUITest_BitmapCheckpoint_DiffImage {
            get {
                return ResourceManager.GetString("GUITest_BitmapCheckpoint_DiffImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected image file: .
        /// </summary>
        internal static string GUITest_BitmapCheckpoint_ExpectedImage {
            get {
                return ResourceManager.GetString("GUITest_BitmapCheckpoint_ExpectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string GUITest_Checkpoint_ActualValue {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string GUITest_Checkpoint_CheckFailed {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string GUITest_Checkpoint_CheckPassed {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_CheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        internal static string GUITest_Checkpoint_ExpectedValue {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string GUITest_Checkpoint_FalseValue {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression.
        /// </summary>
        internal static string GUITest_Checkpoint_IsRegexp {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_IsRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string GUITest_Checkpoint_TrueValue {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_TrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use formula.
        /// </summary>
        internal static string GUITest_Checkpoint_UseFormula {
            get {
                return ResourceManager.GetString("GUITest_Checkpoint_UseFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic match: {0}; Optional match: {1}.
        /// </summary>
        internal static string GUITest_SID_Description {
            get {
                return ResourceManager.GetString("GUITest_SID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_Captured {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_ExactMatch {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_Expected {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore spaces: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_IgnoreSpaces {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_IgnoreSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_IsRegexp {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_IsRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_MatchCase {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text after: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_TextAfter {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_TextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text before: .
        /// </summary>
        internal static string GUITest_TextCheckpoint_TextBefore {
            get {
                return ResourceManager.GetString("GUITest_TextCheckpoint_TextBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JUnit Xml report is generated at: {0}.
        /// </summary>
        internal static string InfoMsg_JUnit_OutputGenerated {
            get {
                return ResourceManager.GetString("InfoMsg_JUnit_OutputGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NUnit 3 Xml report is generated at: {0}.
        /// </summary>
        internal static string InfoMsg_NUnit3_OutputGenerated {
            get {
                return ResourceManager.GetString("InfoMsg_NUnit3_OutputGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Focus UFT Report Converter Tool.
        /// </summary>
        internal static string Prog_Title {
            get {
                return ResourceManager.GetString("Prog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mandatory].
        /// </summary>
        internal static string Prog_Usage_MandatoryOption {
            get {
                return ResourceManager.GetString("Prog_Usage_MandatoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///  {0}.
        /// </summary>
        internal static string Prog_Usage_OneLine {
            get {
                return ResourceManager.GetString("Prog_Usage_OneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Prog_Usage_OptArgsTitle {
            get {
                return ResourceManager.GetString("Prog_Usage_OptArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;options&gt;.
        /// </summary>
        internal static string Prog_Usage_OptionsSection {
            get {
                return ResourceManager.GetString("Prog_Usage_OptionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string Prop_MemoryUnit {
            get {
                return ResourceManager.GetString("Prop_MemoryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string PropName_Action {
            get {
                return ResourceManager.GetString("PropName_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string PropName_ActionDuration {
            get {
                return ResourceManager.GetString("PropName_ActionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action iteration.
        /// </summary>
        internal static string PropName_ActionIteration {
            get {
                return ResourceManager.GetString("PropName_ActionIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action iteration index.
        /// </summary>
        internal static string PropName_ActionIterationIndex {
            get {
                return ResourceManager.GetString("PropName_ActionIterationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string PropName_ActionStartTime {
            get {
                return ResourceManager.GetString("PropName_ActionStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Component path.
        /// </summary>
        internal static string PropName_BPTBCPath {
            get {
                return ResourceManager.GetString("PropName_BPTBCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string PropName_CPUInfo {
            get {
                return ResourceManager.GetString("PropName_CPUInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration.
        /// </summary>
        internal static string PropName_Iteration {
            get {
                return ResourceManager.GetString("PropName_Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration index.
        /// </summary>
        internal static string PropName_IterationIndex {
            get {
                return ResourceManager.GetString("PropName_IterationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        internal static string PropName_Locale {
            get {
                return ResourceManager.GetString("PropName_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login user.
        /// </summary>
        internal static string PropName_LoginUser {
            get {
                return ResourceManager.GetString("PropName_LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string PropName_Memory {
            get {
                return ResourceManager.GetString("PropName_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system.
        /// </summary>
        internal static string PropName_OSInfo {
            get {
                return ResourceManager.GetString("PropName_OSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action input: .
        /// </summary>
        internal static string PropName_Prefix_ActionInputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_ActionInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action iteration input: .
        /// </summary>
        internal static string PropName_Prefix_ActionIterationInputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_ActionIterationInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action iteration output: .
        /// </summary>
        internal static string PropName_Prefix_ActionIterationOutputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_ActionIterationOutputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action output: .
        /// </summary>
        internal static string PropName_Prefix_ActionOutputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_ActionOutputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUT.
        /// </summary>
        internal static string PropName_Prefix_AUT {
            get {
                return ResourceManager.GetString("PropName_Prefix_AUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Component input: .
        /// </summary>
        internal static string PropName_Prefix_BCInputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_BCInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Component output: .
        /// </summary>
        internal static string PropName_Prefix_BCOutputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_BCOutputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case: .
        /// </summary>
        internal static string PropName_Prefix_BPTBranchCase {
            get {
                return ResourceManager.GetString("PropName_Prefix_BPTBranchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration input: .
        /// </summary>
        internal static string PropName_Prefix_IterationInputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_IterationInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration output: .
        /// </summary>
        internal static string PropName_Prefix_IterationOutputParam {
            get {
                return ResourceManager.GetString("PropName_Prefix_IterationOutputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing tool.
        /// </summary>
        internal static string PropName_TestingTool {
            get {
                return ResourceManager.GetString("PropName_TestingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string PropValue_SecondsUnit {
            get {
                return ResourceManager.GetString("PropValue_SecondsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Test_Recovery {
            get {
                return ResourceManager.GetString("Test_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Test_Step {
            get {
                return ResourceManager.GetString("Test_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Focus UFT One.
        /// </summary>
        internal static string TestingToolName_UFT {
            get {
                return ResourceManager.GetString("TestingToolName_UFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The node is skipped with the node type: {0}.
        /// </summary>
        internal static string WarningMsg_Input_SkippedNodeType {
            get {
                return ResourceManager.GetString("WarningMsg_Input_SkippedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Unknown option &apos;{0}&apos;.
        /// </summary>
        internal static string WarningMsg_UnknownOption {
            get {
                return ResourceManager.GetString("WarningMsg_UnknownOption", resourceCulture);
            }
        }
    }
}
