//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace ReportConverter.XmlReport {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Results", Namespace="", IsNullable=false)]
    public partial class ResultsType {
        
        private GeneralInfoType generalInfoField;
        
        private SRFInfoType sRFInfoField;
        
        private ADFInfoType aDFInfoField;
        
        private ReportNodeType reportNodeField;
        
        private string versionField;
        
        /// <remarks/>
        public GeneralInfoType GeneralInfo {
            get {
                return this.generalInfoField;
            }
            set {
                this.generalInfoField = value;
            }
        }
        
        /// <remarks/>
        public SRFInfoType SRFInfo {
            get {
                return this.sRFInfoField;
            }
            set {
                this.sRFInfoField = value;
            }
        }
        
        /// <remarks/>
        public ADFInfoType ADFInfo {
            get {
                return this.aDFInfoField;
            }
            set {
                this.aDFInfoField = value;
            }
        }
        
        /// <remarks/>
        public ReportNodeType ReportNode {
            get {
                return this.reportNodeField;
            }
            set {
                this.reportNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneralInfoType {
        
        private string resultNameField;
        
        private string runStartTimeField;
        
        private string timezoneField;
        
        private string orchestrationToolNameField;
        
        private decimal orchestrationToolVersionField;
        
        private string orchestrationToolVersionStringLiteralField;
        
        private CustomFieldType[] customFieldsField;
        
        /// <remarks/>
        public string ResultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
        
        /// <remarks/>
        public string RunStartTime {
            get {
                return this.runStartTimeField;
            }
            set {
                this.runStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        public string OrchestrationToolName {
            get {
                return this.orchestrationToolNameField;
            }
            set {
                this.orchestrationToolNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrchestrationToolVersion {
            get {
                return this.orchestrationToolVersionField;
            }
            set {
                this.orchestrationToolVersionField = value;
            }
        }
        
        /// <remarks/>
        public string OrchestrationToolVersionStringLiteral {
            get {
                return this.orchestrationToolVersionStringLiteralField;
            }
            set {
                this.orchestrationToolVersionStringLiteralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public CustomFieldType[] CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomFieldType {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceInfoType {
        
        private string deviceTimeField;
        
        private string timeZoneField;
        
        private string[] textField;
        
        /// <remarks/>
        public string DeviceTime {
            get {
                return this.deviceTimeField;
            }
            set {
                this.deviceTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkType {
        
        private string typeField;
        
        private string referenceField;
        
        private string displaynameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestedApplicationType {
        
        private string runtimeEngineInfoField;
        
        private string nameField;
        
        private string pathField;
        
        private string versionField;
        
        private string technologyField;
        
        private string reservedField;
        
        private string[] additionalInfosField;
        
        /// <remarks/>
        public string RuntimeEngineInfo {
            get {
                return this.runtimeEngineInfoField;
            }
            set {
                this.runtimeEngineInfoField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Technology {
            get {
                return this.technologyField;
            }
            set {
                this.technologyField = value;
            }
        }
        
        /// <remarks/>
        public string Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", IsNullable=false)]
        public string[] AdditionalInfos {
            get {
                return this.additionalInfosField;
            }
            set {
                this.additionalInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SnapshotType {
        
        private string referenceField;
        
        private string highlightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string highlight {
            get {
                return this.highlightField;
            }
            set {
                this.highlightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnvironmentType {
        
        private string timezoneField;
        
        private string localeField;
        
        private string userField;
        
        private string cpuInfoField;
        
        private int numberOfCoresField;
        
        private bool numberOfCoresFieldSpecified;
        
        private string totalMemoryField;
        
        private string hostNameField;
        
        private string oSInfoField;
        
        /// <remarks/>
        public string Timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string CpuInfo {
            get {
                return this.cpuInfoField;
            }
            set {
                this.cpuInfoField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfCores {
            get {
                return this.numberOfCoresField;
            }
            set {
                this.numberOfCoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfCoresSpecified {
            get {
                return this.numberOfCoresFieldSpecified;
            }
            set {
                this.numberOfCoresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TotalMemory {
            get {
                return this.totalMemoryField;
            }
            set {
                this.totalMemoryField = value;
            }
        }
        
        /// <remarks/>
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public string OSInfo {
            get {
                return this.oSInfoField;
            }
            set {
                this.oSInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtensionType {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParameterType {
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataType {
        
        private string nameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string outputTextField;
        
        private string errorTextField;
        
        private string toolNameField;
        
        private decimal toolVersionField;
        
        private bool toolVersionFieldSpecified;
        
        private string toolVersionStringLiteralField;
        
        private string descriptionField;
        
        private string startTimeField;
        
        private decimal durationField;
        
        private bool durationFieldSpecified;
        
        private string resultField;
        
        private string resultMessageField;
        
        private ParameterType[] inputParametersField;
        
        private ParameterType[] outputParametersField;
        
        private ExtensionType extensionField;
        
        private int exitCodeField;
        
        private bool exitCodeFieldSpecified;
        
        private EnvironmentType environmentField;
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        private string videoField;
        
        private SnapshotType snapshotField;
        
        private TestedApplicationType[] testedApplicationsField;
        
        private LinkType[] linksField;
        
        private DeviceInfoType deviceInfoField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OutputText {
            get {
                return this.outputTextField;
            }
            set {
                this.outputTextField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public string ToolName {
            get {
                return this.toolNameField;
            }
            set {
                this.toolNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ToolVersion {
            get {
                return this.toolVersionField;
            }
            set {
                this.toolVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToolVersionSpecified {
            get {
                return this.toolVersionFieldSpecified;
            }
            set {
                this.toolVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ToolVersionStringLiteral {
            get {
                return this.toolVersionStringLiteralField;
            }
            set {
                this.toolVersionStringLiteralField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public ParameterType[] InputParameters {
            get {
                return this.inputParametersField;
            }
            set {
                this.inputParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public ParameterType[] OutputParameters {
            get {
                return this.outputParametersField;
            }
            set {
                this.outputParametersField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public int ExitCode {
            get {
                return this.exitCodeField;
            }
            set {
                this.exitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExitCodeSpecified {
            get {
                return this.exitCodeFieldSpecified;
            }
            set {
                this.exitCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EnvironmentType Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Video {
            get {
                return this.videoField;
            }
            set {
                this.videoField = value;
            }
        }
        
        /// <remarks/>
        public SnapshotType Snapshot {
            get {
                return this.snapshotField;
            }
            set {
                this.snapshotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TestedApplication", IsNullable=false)]
        public TestedApplicationType[] TestedApplications {
            get {
                return this.testedApplicationsField;
            }
            set {
                this.testedApplicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", IsNullable=false)]
        public LinkType[] Links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        public DeviceInfoType DeviceInfo {
            get {
                return this.deviceInfoField;
            }
            set {
                this.deviceInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportNodeType {
        
        private DataType dataField;
        
        private ReportNodeType[] reportNodeField;
        
        private string typeField;
        
        /// <remarks/>
        public DataType Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReportNode")]
        public ReportNodeType[] ReportNode {
            get {
                return this.reportNodeField;
            }
            set {
                this.reportNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADFInfoType {
        
        private string aDFReportLinkLabelField;
        
        private string aDFReportLinkField;
        
        /// <remarks/>
        public string ADFReportLinkLabel {
            get {
                return this.aDFReportLinkLabelField;
            }
            set {
                this.aDFReportLinkLabelField = value;
            }
        }
        
        /// <remarks/>
        public string ADFReportLink {
            get {
                return this.aDFReportLinkField;
            }
            set {
                this.aDFReportLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SRFInfoType {
        
        private bool isSRFEnabledField;
        
        private string reportURLField;
        
        /// <remarks/>
        public bool IsSRFEnabled {
            get {
                return this.isSRFEnabledField;
            }
            set {
                this.isSRFEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string ReportURL {
            get {
                return this.reportURLField;
            }
            set {
                this.reportURLField = value;
            }
        }
    }
}
